<!doctype html>



  


<html class="theme-next mist use-motion" lang="zh-Hans">
<head>
  <meta charset="UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>



<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />















  
  
  <link href="/lib/fancybox/source/jquery.fancybox.css?v=2.1.5" rel="stylesheet" type="text/css" />




  
  
  
  

  
    
    
  

  

  

  

  

  
    
    
    <link href="//fonts.googleapis.com/css?family=Lato:300,300italic,400,400italic,700,700italic&subset=latin,latin-ext" rel="stylesheet" type="text/css">
  






<link href="/lib/font-awesome/css/font-awesome.min.css?v=4.6.2" rel="stylesheet" type="text/css" />

<link href="/css/main.css?v=5.1.0" rel="stylesheet" type="text/css" />


  <meta name="keywords" content="nodejs,Errors," />








  <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico?v=5.1.0" />






<meta name="description" content="Errors通常情况下，node.js程序会产生四种类型的错误，分别是

标准的javascript错误，如
EvalError: 当调用eval()方法时抛出错误
SyntaxError: 当JS语法出现错误时，抛出此类错误
RangeError: 当指定的值不在期望的范围内时，抛出此类错误
ReferenceError: 当试图访问没有定义的变量时，抛出此类错误
URIError: 当全局的U">
<meta property="og:type" content="article">
<meta property="og:title" content="Nodejs - Errors">
<meta property="og:url" content="http://yoursite.com/2017/03/21/前端/nodejs/Nodejs.errors/index.html">
<meta property="og:site_name" content="Essviv">
<meta property="og:description" content="Errors通常情况下，node.js程序会产生四种类型的错误，分别是

标准的javascript错误，如
EvalError: 当调用eval()方法时抛出错误
SyntaxError: 当JS语法出现错误时，抛出此类错误
RangeError: 当指定的值不在期望的范围内时，抛出此类错误
ReferenceError: 当试图访问没有定义的变量时，抛出此类错误
URIError: 当全局的U">
<meta property="og:updated_time" content="2017-03-22T00:44:05.000Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Nodejs - Errors">
<meta name="twitter:description" content="Errors通常情况下，node.js程序会产生四种类型的错误，分别是

标准的javascript错误，如
EvalError: 当调用eval()方法时抛出错误
SyntaxError: 当JS语法出现错误时，抛出此类错误
RangeError: 当指定的值不在期望的范围内时，抛出此类错误
ReferenceError: 当试图访问没有定义的变量时，抛出此类错误
URIError: 当全局的U">



<script type="text/javascript" id="hexo.configurations">
  var NexT = window.NexT || {};
  var CONFIG = {
    root: '/',
    scheme: 'Mist',
    sidebar: {"position":"left","display":"post"},
    fancybox: true,
    motion: true,
    duoshuo: {
      userId: '0',
      author: '博主'
    },
    algolia: {
      applicationID: '',
      apiKey: '',
      indexName: '',
      hits: {"per_page":10},
      labels: {"input_placeholder":"Search for Posts","hits_empty":"We didn't find any results for the search: ${query}","hits_stats":"${hits} results found in ${time} ms"}
    }
  };
</script>



  <link rel="canonical" href="http://yoursite.com/2017/03/21/前端/nodejs/Nodejs.errors/"/>





  <title> Nodejs - Errors | Essviv </title>
</head>

<body itemscope itemtype="http://schema.org/WebPage" lang="zh-Hans">

  




<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-76335662-1', 'auto');
  ga('send', 'pageview');
</script>











  
  
    
  

  <div class="container one-collumn sidebar-position-left page-post-detail ">
    <div class="headband"></div>

    <header id="header" class="header" itemscope itemtype="http://schema.org/WPHeader">
      <div class="header-inner"><div class="site-brand-wrapper">
  <div class="site-meta ">
    

    <div class="custom-logo-site-title">
      <a href="/"  class="brand" rel="start">
        <span class="logo-line-before"><i></i></span>
        <span class="site-title">Essviv</span>
        <span class="logo-line-after"><i></i></span>
      </a>
    </div>
      
        <p class="site-subtitle">Dare to be different</p>
      
  </div>

  <div class="site-nav-toggle">
    <button>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
    </button>
  </div>
</div>

<nav class="site-nav">
  

  
    <ul id="menu" class="menu">
      
        
        <li class="menu-item menu-item-home">
          <a href="/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-home"></i> <br />
            
            首页
          </a>
        </li>
      
        
        <li class="menu-item menu-item-archives">
          <a href="/archives" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-archive"></i> <br />
            
            归档
          </a>
        </li>
      
        
        <li class="menu-item menu-item-about">
          <a href="/about" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-user"></i> <br />
            
            关于
          </a>
        </li>
      

      
    </ul>
  

  
</nav>



 </div>
    </header>

    <main id="main" class="main">
      <div class="main-inner">
        <div class="content-wrap">
          <div id="content" class="content">
            

  <div id="posts" class="posts-expand">
    

  

  
  
  

  <article class="post post-type-normal " itemscope itemtype="http://schema.org/Article">
    <link itemprop="mainEntityOfPage" href="http://yoursite.com/2017/03/21/前端/nodejs/Nodejs.errors/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="name" content="Essviv">
      <meta itemprop="description" content="">
      <meta itemprop="image" content="https://github.com/Essviv/images/blob/master/avatar.jpg?raw=true">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="Essviv">
    </span>

    
      <header class="post-header">

        
        
          <h1 class="post-title" itemprop="name headline">
            
            
              
                Nodejs - Errors
              
            
          </h1>
        

        <div class="post-meta">
          <span class="post-time">
            
              <span class="post-meta-item-icon">
                <i class="fa fa-calendar-o"></i>
              </span>
              
                <span class="post-meta-item-text">发表于</span>
              
              <time title="创建于" itemprop="dateCreated datePublished" datetime="2017-03-21T20:19:00+08:00">
                2017-03-21
              </time>
            

            

            
          </span>

          

          
            
              <span class="post-comments-count">
                <span class="post-meta-divider">|</span>
                <span class="post-meta-item-icon">
                  <i class="fa fa-comment-o"></i>
                </span>
                <a href="/2017/03/21/前端/nodejs/Nodejs.errors/#comments" itemprop="discussionUrl">
                  <span class="post-comments-count ds-thread-count" data-thread-key="2017/03/21/前端/nodejs/Nodejs.errors/" itemprop="commentCount"></span>
                </a>
              </span>
            
          

          
          

          

          

          

        </div>
      </header>
    


    <div class="post-body" itemprop="articleBody">

      
      

      
        <h1 id="Errors"><a href="#Errors" class="headerlink" title="Errors"></a>Errors</h1><p>通常情况下，node.js程序会产生四种类型的错误，分别是</p>
<ul>
<li>标准的javascript错误，如<ul>
<li>EvalError: 当调用eval()方法时抛出错误</li>
<li>SyntaxError: 当JS语法出现错误时，抛出此类错误</li>
<li>RangeError: 当指定的值不在期望的范围内时，抛出此类错误</li>
<li>ReferenceError: 当试图访问没有定义的变量时，抛出此类错误</li>
<li>URIError: 当全局的URI处理函数被不正确地使用时，抛出此类错误</li>
</ul>
</li>
<li>底层系统触发的错误，如试图打开一个不存在的文件，或者试图往一个关闭的socket中发送数据时</li>
<li>用户在程序运行的过程中自定义的错误</li>
<li>声明式错误是一类特殊的错误，它是在node.js系统检测到本不应该出现的情况时抛出的错误. 这些错误通常是由assert模块中的方法抛出.</li>
</ul>
<p>所有由node.js抛出的错误, 要么是Error实例，要么是Error子类的实例, 并且node.js系统保证至少能获取到相应错误类的属性值. </p>
<h2 id="Error的传播与捕获"><a href="#Error的传播与捕获" class="headerlink" title="Error的传播与捕获"></a>Error的传播与捕获</h2><p>node.js对程序运行过程中产生的error对象，提供了多种机制对它们进行传播和处理. 这些产生的error对象会如何被报告及处理取决于error的类型，以及API被调用的方式. </p>
<ul>
<li><ol>
<li>所有的JS错误都会以异常的形式被直接抛出，并通过throw机制通知应用程序. 抛出的error对象可以通过try/catch机制进行捕获并处理. </li>
</ol>
</li>
</ul>
<figure class="highlight javascript"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div></pre></td><td class="code"><pre><div class="line"><span class="comment">// Throws with a ReferenceError because z is undefined</span></div><div class="line"><span class="keyword">try</span> &#123;</div><div class="line">  <span class="keyword">const</span> m = <span class="number">1</span>;</div><div class="line">  <span class="keyword">const</span> n = m + z;</div><div class="line">&#125; <span class="keyword">catch</span> (err) &#123;</div><div class="line">  <span class="comment">// Handle the error here.</span></div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>JS中以throw关键字抛出的异常，都必须通过try/catch进行捕获，否则node.js进程将会直接退出. </p>
<ul>
<li><ol>
<li>对于同步API中产生的一些异常(所有不带回调参数的方法，如fs.readFileSync(), 都被认为是同步API),会直接通过throw关键字抛出异常.</li>
</ol>
</li>
<li><ol>
<li>对于异步API中产生的异常，可能会以多种方式报告异常：</li>
</ol>
<ul>
<li>大部分的异步API都接受callback回调函数，该函数在被调用时，第一个参数会保留给Error参数，如果在处理的过程中出现了错误，那么在调用callback回调函数的时候，第一个Error参数就带有错误的详细信息，此时必须处理相应的错误；如果在处理的过程没有发生错误 ，那么error参数为null</li>
</ul>
<figure class="highlight javascript"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">const</span> fs = <span class="built_in">require</span>(<span class="string">'fs'</span>);</div><div class="line">fs.readFile(<span class="string">'a file that does not exist'</span>, (err, data) =&gt; &#123;</div><div class="line">  <span class="keyword">if</span> (err) &#123;</div><div class="line">    <span class="built_in">console</span>.error(<span class="string">'There was an error reading the file!'</span>, err);</div><div class="line">    <span class="keyword">return</span>;</div><div class="line">  &#125;</div><div class="line">  <span class="comment">// Otherwise handle the data</span></div><div class="line">&#125;);</div></pre></td></tr></table></figure>
<ul>
<li>当调用EventEmitter类的异步API时，发生的错误会被路由到error事件：</li>
</ul>
<figure class="highlight javascript"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">const</span> net = <span class="built_in">require</span>(<span class="string">'net'</span>);</div><div class="line"><span class="keyword">const</span> connection = net.connect(<span class="string">'localhost'</span>);</div><div class="line"></div><div class="line"><span class="comment">// Adding an 'error' event handler to a stream:</span></div><div class="line">connection.on(<span class="string">'error'</span>, (err) =&gt; &#123;</div><div class="line">  <span class="comment">// If the connection is reset by the server, or if it can't</span></div><div class="line">  <span class="comment">// connect at all, or on any sort of error encountered by</span></div><div class="line">  <span class="comment">// the connection, the error will be sent here.</span></div><div class="line">  <span class="built_in">console</span>.error(err);</div><div class="line">&#125;);</div><div class="line"></div><div class="line">connection.pipe(process.stdout);</div></pre></td></tr></table></figure>
<ul>
<li>在异步方法的回调函数中，还是可以通过throw关键字将error抛出，这样外部的应用程序就必须通过try/catch机制来捕获并处理异常. 对于这样的方法，没有完整的列表，在需要使用的时候，可以参阅相应的方法说明</li>
</ul>
</li>
</ul>
<p>在使用流和事件相关的API时，在error事件中错误发生的错误是比较常见的做法. 对于所有的EventEmitter对象而言，如果没有提供error事件的处理器，那么error异常将会被抛出，导致node.js进程抛出无法处理的异常，并直接退出, 除非有以下两种情况：</p>
<ul>
<li>使用了domain模块</li>
<li>在process.on(“uncaughtException”)事件上注册了监听器</li>
</ul>
<figure class="highlight javascript"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">const</span> EventEmitter = <span class="built_in">require</span>(<span class="string">'events'</span>);</div><div class="line"><span class="keyword">const</span> ee = <span class="keyword">new</span> EventEmitter();</div><div class="line"></div><div class="line">setImmediate(<span class="function"><span class="params">()</span> =&gt;</span> &#123;</div><div class="line">  <span class="comment">// This will crash the process because no 'error' event</span></div><div class="line">  <span class="comment">// handler has been added.</span></div><div class="line">  ee.emit(<span class="string">'error'</span>, <span class="keyword">new</span> <span class="built_in">Error</span>(<span class="string">'This will crash'</span>));</div><div class="line">&#125;);</div></pre></td></tr></table></figure>
<p>在这种情况下，无法使用try/catch关键字对error异常进行捕获，因为当抛出error错误时，try/catch已经执行完了. 开发者需要查阅相关的文档来了解具体的方法是如何抛出方法中产生的异常.</p>
<h2 id="node-js风格的回调函数"><a href="#node-js风格的回调函数" class="headerlink" title="node.js风格的回调函数"></a>node.js风格的回调函数</h2><p>node.js核心API中的大部分异步方法都使用统一风格的异步回调函数，这种回调函数被称为是“node.js风格的回调函数”. 在这种风格的回调函数中，callback回调函数被作为异步方法的参数传入. 当异步方法执行完成或者抛出异常时，都会回调callback函数. 如果执行的过程中发生了错误，那么在回调函数的第一个Error参数中就带有具体的错误信息，这时候需要对错误进行处理； 如果执行的过程顺利完成，那么第一个Error参数将会被设置成null. </p>
<figure class="highlight javascript"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">const</span> fs = <span class="built_in">require</span>(<span class="string">'fs'</span>);</div><div class="line"></div><div class="line"><span class="function"><span class="keyword">function</span> <span class="title">nodeStyleCallback</span>(<span class="params">err, data</span>) </span>&#123;</div><div class="line"> <span class="keyword">if</span> (err) &#123;</div><div class="line">   <span class="built_in">console</span>.error(<span class="string">'There was an error'</span>, err);</div><div class="line">   <span class="keyword">return</span>;</div><div class="line"> &#125;</div><div class="line"> <span class="built_in">console</span>.log(data);</div><div class="line">&#125;</div><div class="line"></div><div class="line">fs.readFile(<span class="string">'/some/file/that/does-not-exist'</span>, nodeStyleCallback);</div><div class="line">fs.readFile(<span class="string">'/some/file/that/does-exist'</span>, nodeStyleCallback)</div></pre></td></tr></table></figure>
<p><strong>JS中的try/catch关键字不能用于捕获异步方法中抛出的异常. </strong>初学者经常会在回调函数中使用throw关键字重新抛出异常. </p>
<figure class="highlight javascript"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div></pre></td><td class="code"><pre><div class="line"><span class="comment">// THIS WILL NOT WORK:</span></div><div class="line"><span class="keyword">const</span> fs = <span class="built_in">require</span>(<span class="string">'fs'</span>);</div><div class="line"></div><div class="line"><span class="keyword">try</span> &#123;</div><div class="line">  fs.readFile(<span class="string">'/some/file/that/does-not-exist'</span>, (err, data) =&gt; &#123;</div><div class="line">    <span class="comment">// mistaken assumption: throwing here...</span></div><div class="line">    <span class="keyword">if</span> (err) &#123;</div><div class="line">      <span class="keyword">throw</span> err;</div><div class="line">    &#125;</div><div class="line">  &#125;);</div><div class="line">&#125; <span class="keyword">catch</span>(err) &#123;</div><div class="line">  <span class="comment">// This will not catch the throw!</span></div><div class="line">  <span class="built_in">console</span>.log(err);</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>以上的代码无法正常工作，因为传递给fs.readFile()方法的回调函数是被异步调用的. 当callback()方法被调用时，外部的代码(包括try{}catch(){}代码块)已经退出了. 另外，在回调函数中使用throw关键字往往会导致node.js崩溃退出, 除非存在以下两种情况，那么异常会被正常捕获：</p>
<ul>
<li>使用了domain模块</li>
<li>在process.on(“uncaughtException”)事件上注册了监听器</li>
</ul>
<h2 id="Error类"><a href="#Error类" class="headerlink" title="Error类"></a>Error类</h2><p>这个类是通用的JS Error类，它不定义产生错误的具体原因及场景. Error类可以捕获到发生错误时代码的具体位置及相应的调用堆栈详情， 有可能还会提供关于错误的描述. </p>
<p>在node.js中产生的所有错误，包括所有的系统错误及JS错误， 要么是Error类的实例，要么是Error子类的实例. </p>
<h2 id="new-Error-message"><a href="#new-Error-message" class="headerlink" title="new Error(message)"></a>new Error(message)</h2><p>该方法用于创建新的错误对象, 并将error.message属性设置为message. 如果message参数的类型为对象类型，那么error.message的值将会被设置为message.toString()方法返回的值. 另外，error.stack属性的值会被设置成调用new Error()方法时的调用堆栈. 调用堆栈的具体内容取决于V8引擎的堆栈API. 调用堆栈会一直往上追溯到代码的开始位置， 但不会超过Error.stackTraceLimit属性值设置的最大堆栈深度. </p>
<h2 id="Error-captureStackTrace-targetObj-constructorObj"><a href="#Error-captureStackTrace-targetObj-constructorObj" class="headerlink" title="Error.captureStackTrace(targetObj[, constructorObj])"></a>Error.captureStackTrace(targetObj[, constructorObj])</h2><p>该方法在targetObj目标对象上创建stack属性，该属性中记录了创建captureStackTrace()方法时代码的调用堆栈. </p>
<figure class="highlight javascript"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">const</span> myObject = &#123;&#125;;</div><div class="line"><span class="built_in">Error</span>.captureStackTrace(myObject);</div><div class="line">myObject.stack  <span class="comment">// similar to `new Error().stack`</span></div></pre></td></tr></table></figure>
<p>使用这种方式输出调用堆栈时，与普通的错误不同的是，调用堆栈的第一行不是ErrorType: message, 而是targetObject.toString()方法的输出结果. </p>
<p>可选的constructorOpt参数是函数类型，如果给定了constructorOpt参数，包括constructorOpt参数本身， 都不会出现在输出的调用堆栈中. 这种机制在需要向终端用户隐藏内部实现细节时非常有用. 例如：</p>
<figure class="highlight javascript"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div></pre></td><td class="code"><pre><div class="line"><span class="function"><span class="keyword">function</span> <span class="title">MyError</span>(<span class="params"></span>) </span>&#123;</div><div class="line">  <span class="built_in">Error</span>.captureStackTrace(<span class="keyword">this</span>, MyError);</div><div class="line">&#125;</div><div class="line"></div><div class="line"><span class="comment">// Without passing MyError to captureStackTrace, the MyError</span></div><div class="line"><span class="comment">// frame would show up in the .stack property. By passing</span></div><div class="line"><span class="comment">// the constructor, we omit that frame and all frames above it.</span></div><div class="line"><span class="keyword">new</span> MyError().stack</div></pre></td></tr></table></figure>
<h2 id="Error-stackTraceLimit"><a href="#Error-stackTraceLimit" class="headerlink" title="Error.stackTraceLimit"></a>Error.stackTraceLimit</h2><p>该属性值定义了在收集代码调用堆栈时最大的栈帧数（不管是通过new Error().stack属性还是通过Error.captureStackTrace(obj)方法). 该属性值默认为10，但可以更改成任何有效的js数字. 修改完该属性值后，后续所有收集调用堆栈时都会使用这个值. 如果这个值被设置成非数字类型，或者被设置成负数值， 那么当需要收集调用堆栈时，将不会执行任何操作. </p>
<h2 id="error-message"><a href="#error-message" class="headerlink" title="error.message"></a>error.message</h2><p>该属性记录了在调用new Error(message)方法时设置的message值. 传递给构造函数的message值会出现在调用堆栈的第一行中，但如果在构建完error对象后修改了message属性的值，这个修改后的值有可能不会出现在第一行中.</p>
<figure class="highlight javascript"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">const</span> err = <span class="keyword">new</span> <span class="built_in">Error</span>(<span class="string">'The message'</span>);</div><div class="line"><span class="built_in">console</span>.log(err.message);</div><div class="line"><span class="comment">// Prints: The message</span></div></pre></td></tr></table></figure>
<h2 id="error-stack"><a href="#error-stack" class="headerlink" title="error.stack"></a>error.stack</h2><p>该属性返回Error创建时代码的调用堆栈，类型为字符串类型. 例如：</p>
<figure class="highlight javascript"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div></pre></td><td class="code"><pre><div class="line"><span class="built_in">Error</span>: Things keep happening!</div><div class="line">   at /home/gbusey/file.js:<span class="number">525</span>:<span class="number">2</span></div><div class="line">   at Frobnicator.refrobulate (<span class="regexp">/home/g</span>busey/business-logic.js:<span class="number">424</span>:<span class="number">21</span>)</div><div class="line">   at Actor.&lt;anonymous&gt; (<span class="regexp">/home/g</span>busey/actors.js:<span class="number">400</span>:<span class="number">8</span>)</div><div class="line">   at increaseSynergy (<span class="regexp">/home/g</span>busey/actors.js:<span class="number">701</span>:<span class="number">6</span>)</div></pre></td></tr></table></figure>
<p>输出的调用堆栈的第一行格式为<error class="" name="">: <error message="">，后面跟着一系列的栈帧, 每个栈帧都表示一行代码调用，这些栈帧是导致Error异常被抛出的代码. V8引擎会尝试为每个栈帧显示相应的名称（可能是变量名称，也可能是函数名称，也可以是对象方法名称），但有时候引擎没有办法找到合适的名称. 如果V8引擎无法为方法找到合适的名称，那么只会显示那一帧的位置信息. 否则，将会显示相应的名称，并把位置信息加到名称的后面. </error></error></p>
<p>另外，值得注意的，node.js只会为JS函数的栈帧生成堆栈. 例如在下面的例子中，当执行顺序被传递给C++插件cheetahify，在cheetahify中调用了JS方法，那么在输出的栈帧中，并不会包含有cheetahify方法的信息：</p>
<figure class="highlight javascript"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div><div class="line">21</div><div class="line">22</div><div class="line">23</div><div class="line">24</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">const</span> cheetahify = <span class="built_in">require</span>(<span class="string">'./native-binding.node'</span>);</div><div class="line"></div><div class="line"><span class="function"><span class="keyword">function</span> <span class="title">makeFaster</span>(<span class="params"></span>) </span>&#123;</div><div class="line">  <span class="comment">// cheetahify *synchronously* calls speedy.</span></div><div class="line">  cheetahify(<span class="function"><span class="keyword">function</span> <span class="title">speedy</span>(<span class="params"></span>) </span>&#123;</div><div class="line">    <span class="keyword">throw</span> <span class="keyword">new</span> <span class="built_in">Error</span>(<span class="string">'oh no!'</span>);</div><div class="line">  &#125;);</div><div class="line">&#125;</div><div class="line"></div><div class="line">makeFaster(); <span class="comment">// will throw:</span></div><div class="line">  <span class="comment">// /home/gbusey/file.js:6</span></div><div class="line">  <span class="comment">//     throw new Error('oh no!');</span></div><div class="line">  <span class="comment">//           ^</span></div><div class="line">  <span class="comment">// Error: oh no!</span></div><div class="line">  <span class="comment">//     at speedy (/home/gbusey/file.js:6:11)</span></div><div class="line">  <span class="comment">//     at makeFaster (/home/gbusey/file.js:5:3)</span></div><div class="line">  <span class="comment">//     at Object.&lt;anonymous&gt; (/home/gbusey/file.js:10:1)</span></div><div class="line">  <span class="comment">//     at Module._compile (module.js:456:26)</span></div><div class="line">  <span class="comment">//     at Object.Module._extensions..js (module.js:474:10)</span></div><div class="line">  <span class="comment">//     at Module.load (module.js:356:32)</span></div><div class="line">  <span class="comment">//     at Function.Module._load (module.js:312:12)</span></div><div class="line">  <span class="comment">//     at Function.Module.runMain (module.js:497:10)</span></div><div class="line">  <span class="comment">//     at startup (node.js:119:16)</span></div><div class="line">  <span class="comment">//     at node.js:906:3</span></div></pre></td></tr></table></figure>
<p>另外，在输出的调用堆栈中的位置信息是以下中的一种：</p>
<ul>
<li>native: 当前栈帧是V8引擎的内部方法调用</li>
<li>plain-filename.js: line : column: 当前栈帧是node.js内部方法的调用 </li>
<li>/absolute/path/to/file.js : line : column: 当前栈帧是用户程序或相关依赖的调用</li>
</ul>
<p>error.stack属性的字符串只会在它被访问的时候才会生成. 另外，输出的堆栈的深度取决于Error.stackTraceLimit属性和当前调用堆栈深度的最小值. </p>
<p>系统级别的错误请参见“系统错误”章节.</p>
<h2 id="RangeError类"><a href="#RangeError类" class="headerlink" title="RangeError类"></a>RangeError类</h2><p>RangeError类是Error类的子类，它标识了提供的参数值不在可接受的范围值之内， 这包括两种情况：</p>
<ul>
<li>提供的数值不在方法期望的数据范围内</li>
<li>提供的参数不在方法期望的参数集合内</li>
</ul>
<p>例如：</p>
<figure class="highlight javascript"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div></pre></td><td class="code"><pre><div class="line"><span class="built_in">require</span>(<span class="string">'net'</span>).connect(<span class="number">-1</span>);</div><div class="line">  <span class="comment">// throws RangeError, port should be &gt; 0 &amp;&amp; &lt; 65536</span></div></pre></td></tr></table></figure>
<p>node.js会以参数校验的方式直接生成并抛出Error对象.</p>
<h2 id="ReferenceError类"><a href="#ReferenceError类" class="headerlink" title="ReferenceError类"></a>ReferenceError类</h2><p>ReferenceError类是Error类的子类，它标识了尝试访问的某个变量值没有被定义, 此类错误通常意味着拼写的错误或程序出现了错误. 虽然说客户端代码也可以产生和抛出这类错误，但通常来讲，此类错误应该由V8引擎抛出： </p>
<figure class="highlight javascript"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div></pre></td><td class="code"><pre><div class="line">doesNotExist;</div><div class="line">  <span class="comment">// throws ReferenceError, doesNotExist is not a variable in this program.</span></div></pre></td></tr></table></figure>
<p>ReferenceError类的实例会带有error.arguments属性，该属性是个数组，数组只有一个字符串类型的元素，该元素标识了未被定义的变量名称. </p>
<figure class="highlight javascript"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">const</span> assert = <span class="built_in">require</span>(<span class="string">'assert'</span>);</div><div class="line"><span class="keyword">try</span> &#123;</div><div class="line">  doesNotExist;</div><div class="line">&#125; <span class="keyword">catch</span>(err) &#123;</div><div class="line">  assert(err.arguments[<span class="number">0</span>], <span class="string">'doesNotExist'</span>);</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>除非程序的执行代码是动态生成的，否则当遇到ReferenceError错误时，就应该认为执行代码或者其相关的依赖中存在bug. </p>
<h2 id="SyntaxError"><a href="#SyntaxError" class="headerlink" title="SyntaxError"></a>SyntaxError</h2><p>SyntaxError类也是Error类的子类，这类错误标识了运行的代码不是有效的JS代码. 这类错误只会在代码执行的时候产生并抛出. 代码执行可以是通过eval方法， Function方法， require方法或者VM模块. 此类错误往往意味着运行的代码不是有效的JS代码. </p>
<figure class="highlight javascript"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">try</span> &#123;</div><div class="line">  <span class="built_in">require</span>(<span class="string">'vm'</span>).runInThisContext(<span class="string">'binary ! isNotOk'</span>);</div><div class="line">&#125; <span class="keyword">catch</span>(err) &#123;</div><div class="line">  <span class="comment">// err will be a SyntaxError</span></div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>SyntaxError错误在产生它的上下文中无法被恢复，但可以在其它上下文中恢复. </p>
<h2 id="TypeError"><a href="#TypeError" class="headerlink" title="TypeError"></a>TypeError</h2><p>TypeError也是Error类的子类，此类错误标识了提供的参数类型不是所期望的类型. 例如， 向需要字符串类型的方法中传递了函数类型的变量，就会抛出TypeError错误. </p>
<figure class="highlight javascript"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div></pre></td><td class="code"><pre><div class="line"><span class="built_in">require</span>(<span class="string">'url'</span>).parse(<span class="function"><span class="params">()</span> =&gt;</span> &#123; &#125;);</div><div class="line">  <span class="comment">// throws TypeError, since it expected a string</span></div></pre></td></tr></table></figure>
<p>node.js会以参数校验的方式直接生成并抛出Error对象.</p>
<h2 id="异常-vs-错误"><a href="#异常-vs-错误" class="headerlink" title="异常 vs. 错误"></a>异常 vs. 错误</h2><p>JS异常是由于无效的操作或调用了throw操作导致的结果. 虽然并不要求异常一定是Error类的实例，或者是Error子类的实例，但是在node.js系统或者js运行时中抛出的异常都是Error类的实例. </p>
<p>有些异常在JS层是无法恢复的， 这些异常往往会导致node.js进程崩溃并退出. 这些异常包括assert()声明异常或者是在c++层调用了abort()方法. </p>
<h2 id="系统异常"><a href="#系统异常" class="headerlink" title="系统异常"></a>系统异常</h2><p>系统异常通常是由于程序的运行时环境中出现了异常的时候抛出. 通常情况下，这是由于一些操作违背了操作系统的限制导致的，如尝试读取不存在的文件，或者当用户没有足够的权限执行相应的操作时，会抛出此类异常. </p>
<p>系统异常通常是在syscall层面产生的: 这些异常的代码列表及相应的含义可以通过man 2 intro或者man 3 errno查看，或者查阅相应的在线文档. </p>
<p>在node.js中，系统错误通过加强的Error实例对象来表示，这些对象中带有额外的属性信息. </p>
<h2 id="SystemError类"><a href="#SystemError类" class="headerlink" title="SystemError类"></a>SystemError类</h2><h2 id="error-code"><a href="#error-code" class="headerlink" title="error.code"></a>error.code</h2><p>该属性代表了错误码，通常情况下是以大宝的“E”开始，后面加上一系列的大写字母来表示，具体的含义可以通过man 2 intro来查看.</p>
<h2 id="error-errno"><a href="#error-errno" class="headerlink" title="error.errno"></a>error.errno</h2><p>该属性代表相应的错误代码，数值类型，具体的值及含义可通过man 2 intro来查看. 例如： ENOENT错误码对应的错误代码为-2. </p>
<h2 id="error-syscall"><a href="#error-syscall" class="headerlink" title="error.syscall"></a>error.syscall</h2><p>该属性代表调用失败的syscall描述. </p>
<h2 id="常见的系统错误"><a href="#常见的系统错误" class="headerlink" title="常见的系统错误"></a>常见的系统错误</h2><p>本列表并没有列出完整的错误列表，但列举了在写node.js程序中最经常遇见的系统错误. </p>
<ul>
<li>EACCES: 无权限访问，此错误在尝试访问某个没有权限访问的文件时出现</li>
<li>EADDRINUSE: 地址已经被占用. 此错误在尝试将服务的地址绑定到某个已经被其它服务占用的地址时出现</li>
<li>ECONNREFUSED: 连接被拒绝，此错误往往在尝试连接外部的某个服务时，外部服务主动拒绝请求时出现，这通常意味着外部服务处于不可用的状态.</li>
<li>ECONNRESET: 连接被重置. 此错误通常在某个连接被强制关闭时出现. 这通常是由于连接超时或重启导致连接断开，经常出现在http和net模块</li>
<li>EEXIST: 文件已存在. 此错误出现在当某个操作要求目标文件不存在 ，但事实上已经存在时产生</li>
<li>EISDIR: 指定的文件是个目录. 此错误在某个操作期望指定的路径是个文件，但事实上是个目录时产生</li>
<li>EMFILE: 打开太多的文件句柄. 此错误出现在当前打开的文件句柄数超过了系统设置的最大值，当再次请求打开文件句柄时出现. 为了避免设置的文件句柄数过低，可以通过ulimit -n 2048来进行设置</li>
<li>ENOENT: 找不到文件或目录. 此错误通常出现在fs模块中，当指定的文件名不存在时抛出此类错误</li>
<li>ENOTDIR: 指定的路径不是目录. 此错误出现在指定的文件存在，但不是目录类型时产生，通常出现在fs.readdir()中</li>
<li>ENOTEMPTY: 不是空目录. 当执行的操作要求目录为空目录，而事实上指定的目录并不是空的时候出现此类错误</li>
<li>EPERM: 禁止操作. 当尝试执行的操作需要提权才能进行时，抛出此类错误</li>
<li>EPIPE: Broken pipe. 当尝试向已经关闭的pipe, socket以及FIFO设备写入数据时，抛出此类错误. 通常在net和http模块中出现，此类错误往往意味着正在写入的通道已经被关闭了. </li>
<li>ETIMEOUT: 操作超时. 由于对方没有及时响应，导致连接或执行的操作超时时抛出此类错误. 通常在http和net模块中出现，这类错误往往意味着socket.end()方法没有被正确地关闭.</li>
</ul>
<h1 id="参考文献"><a href="#参考文献" class="headerlink" title="参考文献"></a>参考文献</h1><ol>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html" target="_blank" rel="external">官方文档</a></li>
</ol>

      
    </div>

    <div>
      
        

      
    </div>

    <div>
      
        
  <div style="padding: 10px 0; margin: 20px auto; width: 90%; text-align: center;">
    <div>您的支持将鼓励我继续创作！</div>
    <button id="rewardButton" disable="enable" onclick="var qr = document.getElementById('QR'); if (qr.style.display === 'none') {qr.style.display='block';} else {qr.style.display='none'}">
      <span>赏</span>
    </button>
    <div id="QR" style="display: none;">
      
        <div id="wechat" style="display: inline-block">
          <img id="wechat_qr" src="https://github.com/Essviv/images/blob/master/wechat.jpg?raw=true" alt="Essviv WeChat Pay"/>
          <p>微信打赏</p>
        </div>
      
      
        <div id="alipay" style="display: inline-block">
          <img id="alipay_qr" src="https://github.com/Essviv/images/blob/master/alipay.jpg?raw=true" alt="Essviv Alipay"/>
          <p>支付宝打赏</p>
        </div>
      
    </div>
  </div>


      
    </div>


    <footer class="post-footer">
      
        <div class="post-tags">
          
            <a href="/tags/nodejs/" rel="tag"># nodejs</a>
          
            <a href="/tags/Errors/" rel="tag"># Errors</a>
          
        </div>
      

      
        
      

      
        <div class="post-nav">
          <div class="post-nav-next post-nav-item">
            
              <a href="/2017/03/21/前端/nodejs/Nodejs.stringDecoder/" rel="next" title="nodejs - StringDecoder">
                <i class="fa fa-chevron-left"></i> nodejs - StringDecoder
              </a>
            
          </div>

          <span class="post-nav-divider"></span>

          <div class="post-nav-prev post-nav-item">
            
              <a href="/2017/03/22/前端/nodejs/Nodejs.queryString/" rel="prev" title="nodejs - queryString">
                nodejs - queryString <i class="fa fa-chevron-right"></i>
              </a>
            
          </div>
        </div>
      

      
      
    </footer>
  </article>



    <div class="post-spread">
      
    </div>
  </div>

          
          </div>
          


          
  <div class="comments" id="comments">
    
      <div class="ds-thread" data-thread-key="2017/03/21/前端/nodejs/Nodejs.errors/"
           data-title="Nodejs - Errors" data-url="http://yoursite.com/2017/03/21/前端/nodejs/Nodejs.errors/">
      </div>
    
  </div>


        </div>
        
          
  
  <div class="sidebar-toggle">
    <div class="sidebar-toggle-line-wrap">
      <span class="sidebar-toggle-line sidebar-toggle-line-first"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-middle"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-last"></span>
    </div>
  </div>

  <aside id="sidebar" class="sidebar">
    <div class="sidebar-inner">

      

      
        <ul class="sidebar-nav motion-element">
          <li class="sidebar-nav-toc sidebar-nav-active" data-target="post-toc-wrap" >
            文章目录
          </li>
          <li class="sidebar-nav-overview" data-target="site-overview">
            站点概览
          </li>
        </ul>
      

      <section class="site-overview sidebar-panel">
        <div class="site-author motion-element" itemprop="author" itemscope itemtype="http://schema.org/Person">
          <img class="site-author-image" itemprop="image"
               src="https://github.com/Essviv/images/blob/master/avatar.jpg?raw=true"
               alt="Essviv" />
          <p class="site-author-name" itemprop="name">Essviv</p>
           
              <p class="site-description motion-element" itemprop="description"></p>
          
        </div>
        <nav class="site-state motion-element">

          
            <div class="site-state-item site-state-posts">
              <a href="/archives">
                <span class="site-state-item-count">170</span>
                <span class="site-state-item-name">日志</span>
              </a>
            </div>
          

          

          
            
            
            <div class="site-state-item site-state-tags">
              
                <span class="site-state-item-count">48</span>
                <span class="site-state-item-name">标签</span>
              
            </div>
          

        </nav>

        

        <div class="links-of-author motion-element">
          
            
              <span class="links-of-author-item">
                <a href="https://github.com/essviv" target="_blank" title="GitHub">
                  
                    <i class="fa fa-fw fa-github"></i>
                  
                  GitHub
                </a>
              </span>
            
          
        </div>

        
        

        
        

        


      </section>

      
      <!--noindex-->
        <section class="post-toc-wrap motion-element sidebar-panel sidebar-panel-active">
          <div class="post-toc">

            
              
            

            
              <div class="post-toc-content"><ol class="nav"><li class="nav-item nav-level-1"><a class="nav-link" href="#Errors"><span class="nav-text">Errors</span></a><ol class="nav-child"><li class="nav-item nav-level-2"><a class="nav-link" href="#Error的传播与捕获"><span class="nav-text">Error的传播与捕获</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#node-js风格的回调函数"><span class="nav-text">node.js风格的回调函数</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#Error类"><span class="nav-text">Error类</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#new-Error-message"><span class="nav-text">new Error(message)</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#Error-captureStackTrace-targetObj-constructorObj"><span class="nav-text">Error.captureStackTrace(targetObj[, constructorObj])</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#Error-stackTraceLimit"><span class="nav-text">Error.stackTraceLimit</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#error-message"><span class="nav-text">error.message</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#error-stack"><span class="nav-text">error.stack</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#RangeError类"><span class="nav-text">RangeError类</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#ReferenceError类"><span class="nav-text">ReferenceError类</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#SyntaxError"><span class="nav-text">SyntaxError</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#TypeError"><span class="nav-text">TypeError</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#异常-vs-错误"><span class="nav-text">异常 vs. 错误</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#系统异常"><span class="nav-text">系统异常</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#SystemError类"><span class="nav-text">SystemError类</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#error-code"><span class="nav-text">error.code</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#error-errno"><span class="nav-text">error.errno</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#error-syscall"><span class="nav-text">error.syscall</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#常见的系统错误"><span class="nav-text">常见的系统错误</span></a></li></ol></li><li class="nav-item nav-level-1"><a class="nav-link" href="#参考文献"><span class="nav-text">参考文献</span></a></li></ol></div>
            

          </div>
        </section>
      <!--/noindex-->
      

      

    </div>
  </aside>


        
      </div>
    </main>

    <footer id="footer" class="footer">
      <div class="footer-inner">
        <div class="copyright" >
  
  &copy; 
  <span itemprop="copyrightYear">2017</span>
  <span class="with-love">
    <i class="fa fa-heart"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">Essviv</span>
</div>


<div class="powered-by">
  由 <a class="theme-link" href="https://hexo.io">Hexo</a> 强力驱动
</div>

<div class="theme-info">
  主题 -
  <a class="theme-link" href="https://github.com/iissnan/hexo-theme-next">
    NexT.Mist
  </a>
</div>


        

        
      </div>
    </footer>

    
      <div class="back-to-top">
        <i class="fa fa-arrow-up"></i>
        
      </div>
    
    
  </div>

  

<script type="text/javascript">
  if (Object.prototype.toString.call(window.Promise) !== '[object Function]') {
    window.Promise = null;
  }
</script>









  




  
  <script type="text/javascript" src="/lib/jquery/index.js?v=2.1.3"></script>

  
  <script type="text/javascript" src="/lib/fastclick/lib/fastclick.min.js?v=1.0.6"></script>

  
  <script type="text/javascript" src="/lib/jquery_lazyload/jquery.lazyload.js?v=1.9.7"></script>

  
  <script type="text/javascript" src="/lib/velocity/velocity.min.js?v=1.2.1"></script>

  
  <script type="text/javascript" src="/lib/velocity/velocity.ui.min.js?v=1.2.1"></script>

  
  <script type="text/javascript" src="/lib/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>


  


  <script type="text/javascript" src="/js/src/utils.js?v=5.1.0"></script>

  <script type="text/javascript" src="/js/src/motion.js?v=5.1.0"></script>



  
  

  
  <script type="text/javascript" src="/js/src/scrollspy.js?v=5.1.0"></script>
<script type="text/javascript" src="/js/src/post-details.js?v=5.1.0"></script>



  


  <script type="text/javascript" src="/js/src/bootstrap.js?v=5.1.0"></script>



  

  
    
  

  <script type="text/javascript">
    var duoshuoQuery = {short_name:"essviv"};
    (function() {
      var ds = document.createElement('script');
      ds.type = 'text/javascript';ds.async = true;
      ds.id = 'duoshuo-script';
      ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
      ds.charset = 'UTF-8';
      (document.getElementsByTagName('head')[0]
      || document.getElementsByTagName('body')[0]).appendChild(ds);
    })();
  </script>

  
    
    
    <script src="/lib/ua-parser-js/dist/ua-parser.min.js?v=0.7.9"></script>
    <script src="/js/src/hook-duoshuo.js"></script>
  













  
  

  

  

  

  


  

</body>
</html>
